name: Build, lint and test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: 'Install Dependencies'
        id: install
        run: yarn

      - name: Run prettier
        run: yarn prettier -c ./src

      - name: Run eslint
        run: yarn eslint ./src --color --max-warnings 0

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: 'Install Dependencies'
        id: install
        run: yarn

      - name: 'Build Project'
        id: build
        run: yarn build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: 'Install Dependencies'
        id: install
        run: yarn

      - name: Run rests
        run: yarn test

